name: eShop Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln
    - name: Build ./eShopOnWeb.sln --configuration Release
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --configuration Release
